addons:
  sonarcloud:
    organization: "mariemamari"
    token:
      secure: "0d2af8a23d9c7df5e6bfb92f8efc5387228bf6f6" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=mariemamari_formationjava